version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo 'Phase "install"'
      - npm install

  pre_build:
    commands:
      - echo 'Phase "pre_build"'
      - npm run test

  build:
    commands:
      - echo 'Phase "build"'
      - npm run build
      - rm -rf ./node_modules
      - npm install --production

reports:
  reportGroupJunit:
    files:
      - "output/junit.xml"
    file-format: JUNITXML
    discard-paths: yes
